"""
Multi-Dimensional Case Representation Engine for MindVision.

Stage 1 Architecture:
Preserves user-stated facts, multiple interacting concerns, emotions, appraisals,
uncertainty, controllability, and support needs as separate, traceable fields.

Core Principles:
1. Strict separation of Stated Information (explicit) from Inferred Information (model hypotheses).
2. Explicit vs. Predicted emotions (user's words vs classifier scores).
3. Zero invention of visual details or premature psychological decisions (no forced CBT, no generic boilerplate).
4. Explicit tracking of Unknowns / Unstated information.
5. Full semantic traceability back to source text spans.
6. Robust handling of compound, ambiguous, misspelled, and partial inputs.
"""

import re
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Any, Optional, Tuple

import spacy

_nlp = None


def get_spacy_nlp():
    global _nlp
    if _nlp is None:
        try:
            _nlp = spacy.load("en_core_web_sm")
        except Exception:
            _nlp = spacy.blank("en")
            if "sentencizer" not in _nlp.pipe_names:
                _nlp.add_pipe("sentencizer")
    return _nlp


# =============================================================================
# 1. DATA CONTRACTS (Typed, Validated, Explicit Separation)
# =============================================================================

@dataclass
class StatedFact:
    """A concrete entity, actor, event, or condition explicitly mentioned by the user."""
    text: str
    category: str          # "actor", "milestone", "condition", "activity", "obligation", "event"
    source_span: str       # Exact verbatim substring from raw text
    start_char: int
    end_char: int

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class StatedEmotion:
    """An emotional state explicitly verbalized by the user."""
    emotion_word: str      # Exact verbatim word or lemma (e.g. "scared", "happy", "worried")
    valence: str           # "negative", "positive", "ambivalent"
    target: Optional[str]  # What the emotion is directed at (if syntactically attached)
    source_span: str       # Verbatim clause or phrase
    start_char: int
    end_char: int

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class PredictedEmotion:
    """An emotion prediction generated by an external classifier (e.g. RoBERTa ONNX)."""
    label: str
    score: float           # 0.0 to 1.0
    source_model: str = "roberta-goemotions-onnx"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class StatedThoughtOrClaim:
    """A verbatim thought, belief, evaluation, or question stated by the user."""
    statement: str         # e.g. "I haven't done enough", "I'll disappoint my family"
    source_span: str       # Exact verbatim substring
    start_char: int
    end_char: int

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class InferredAppraisal:
    """A model-inferred psychological appraisal, marked explicitly as a hypothesis."""
    dimension: str         # "social_comparison", "career_horizon_uncertainty", "evaluation_fear", "perceived_deficit", "locus_of_control", "temporal_focus"
    interpretation: str    # Human-readable explanation
    confidence: float      # 0.0 to 1.0
    status: str = "hypothesized"  # Always marked as hypothesis, never established fact
    evidence_spans: List[str] = field(default_factory=list)
    reasoning: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class UncertaintyProfile:
    """Assessment of genuine uncertainty vs. predictable facts."""
    has_uncertainty: bool
    uncertainty_type: Optional[str] = None  # "future_outcome", "relational_ambivalence", "decision_doubt", "unclear"
    is_inherently_unpredictable: bool = False
    preservation_required: bool = False     # If True, system must hold space, not force false reassurance
    evidence_spans: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ControllabilityAnalysis:
    """Delineation of potentially controllable vs. uncontrollable factors as hypotheses."""
    potentially_controllable: List[str] = field(default_factory=list)
    potentially_uncontrollable: List[str] = field(default_factory=list)
    confidence: float = 0.5
    status: str = "inferred_hypothesis"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class SupportNeedsHypothesis:
    """Potential support modalities based on the case, without imposing CBT."""
    possible_needs: List[str] = field(default_factory=list)  # e.g. ["validation", "perspective_differentiation", "practical_structuring", "holding_space"]
    contraindications: List[str] = field(default_factory=list) # e.g. ["do_not_minimize_external_barrier", "do_not_force_premature_action"]
    status: str = "uncertain_hypothesis"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class UnknownOrUnstatedInfo:
    """Explicitly tracks what the user has NOT provided to prevent hallucinations."""
    missing_aspects: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CaseRepresentation:
    """
    Comprehensive, multi-dimensional context representation.
    Preserves all user-stated information and isolates inferences with full traceability.
    """
    raw_text: str
    stated_facts: List[StatedFact] = field(default_factory=list)
    stated_emotions: List[StatedEmotion] = field(default_factory=list)
    predicted_emotions: List[PredictedEmotion] = field(default_factory=list)
    stated_thoughts: List[StatedThoughtOrClaim] = field(default_factory=list)
    interacting_concerns: List[str] = field(default_factory=list)
    inferred_appraisals: List[InferredAppraisal] = field(default_factory=list)
    uncertainty: UncertaintyProfile = field(default_factory=lambda: UncertaintyProfile(has_uncertainty=False))
    controllability: ControllabilityAnalysis = field(default_factory=ControllabilityAnalysis)
    support_needs: SupportNeedsHypothesis = field(default_factory=SupportNeedsHypothesis)
    unknowns: UnknownOrUnstatedInfo = field(default_factory=UnknownOrUnstatedInfo)
    traceability_map: Dict[str, List[str]] = field(default_factory=dict)
    is_partial: bool = False
    descriptive_summary: str = ""
    # Grounded Person-Centred Formulation fields (NICE NG136, CBT, ACT)
    stated_behaviors: List[str] = field(default_factory=list)
    context: str = ""
    needs_or_concerns: List[str] = field(default_factory=list)
    tentative_interpretations: List[str] = field(default_factory=list)
    user_goal: Optional[str] = None
    confidence_or_uncertainty: float = 0.5
    ambiguity_level: str = "sufficient"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# =============================================================================
# 2. LINGUISTIC EXTRACTION HELPERS (spaCy Parsing & Entity Mapping)
# =============================================================================

_ACTOR_KEYWORDS = {
    "friends": "actor", "friend": "actor", "family": "actor", "parents": "actor",
    "mother": "actor", "father": "actor", "mom": "actor", "dad": "actor",
    "brother": "actor", "sister": "actor", "siblings": "actor", "son": "actor", "daughter": "actor",
    "child": "actor", "children": "actor", "partner": "actor", "partners": "actor",
    "supervisor": "actor", "boss": "actor", "colleague": "actor", "colleagues": "actor",
    "coworker": "actor", "coworkers": "actor", "peers": "actor", "peer": "actor",
    "boyfriend": "actor", "girlfriend": "actor", "team": "actor", "manager": "actor",
    "person": "actor", "someone": "actor", "ex": "actor", "roommate": "actor", "roommates": "actor",
    "landlord": "actor", "professor": "actor", "professors": "actor", "teacher": "actor",
    "student": "actor", "students": "actor", "teammate": "actor", "teammates": "actor",
    "coach": "actor", "doctor": "actor", "therapist": "actor", "classmate": "actor", "classmates": "actor",
}

_MILESTONE_KEYWORDS = {
    "graduation": "milestone", "career": "domain", "job": "domain", "placement": "milestone",
    "placed": "milestone", "promotion": "milestone", "promoted": "milestone",
    "dating": "relationship", "relationship": "relationship", "partner": "relationship",
    "reciprocate": "relationship", "reciprocation": "relationship", "reconnect": "relationship",
    "report": "document", "environmental report": "document", "planet": "macro_context",
    "interview": "event", "exam": "event", "test": "event", "presentation": "event",
    "meeting": "event", "assignments": "obligation", "manuscript": "creative_work",
    "project": "obligation", "dinner party": "event", "flare-up": "condition",
    "autoimmune": "condition", "laundry": "activity", "fridge": "condition",
    "priority": "stated_concern", "priorities": "stated_concern",
    "content": "activity", "video": "activity", "videos": "activity",
    "work": "obligation", "workload": "obligation", "tasks": "obligation", "task": "obligation",
    "responsibilities": "obligation", "deadlines": "obligation", "stuff": "obligation",
    "canvas": "creative_work", "brushstroke": "creative_work", "brushstrokes": "creative_work",
    "painting": "creative_work", "art": "creative_work", "writing": "creative_work",
    "rent": "obligation", "tuition": "obligation", "bills": "obligation", "mortgage": "obligation",
    "debt": "obligation", "meals": "activity", "food": "activity",
    "acl": "condition", "knee": "condition", "injury": "condition", "crutches": "condition",
    "pain": "condition", "surgery": "condition", "rehab": "activity", "rehabilitation": "activity",
    "soccer": "activity", "sport": "activity", "sports": "activity", "tryouts": "event",
    "code": "obligation", "grade": "milestone", "grades": "milestone", "course": "obligation",
}

_EMOTION_LEXICON = {
    "worried": ("negative", "worry/anxiety"),
    "worry": ("negative", "worry/anxiety"),
    "worries": ("negative", "worry/anxiety"),
    "scared": ("negative", "fear"),
    "fear": ("negative", "fear"),
    "afraid": ("negative", "fear"),
    "happy": ("positive", "joy/sympathy"),
    "glad": ("positive", "joy/sympathy"),
    "guilty": ("negative", "guilt"),
    "guilt": ("negative", "guilt"),
    "furious": ("negative", "anger"),
    "angry": ("negative", "anger"),
    "hopeless": ("negative", "despair"),
    "overwhelmed": ("negative", "overwhelm"),
    "overwhelming": ("negative", "overwhelm"),
    "overwhelm": ("negative", "overwhelm"),
    "powerless": ("negative", "powerlessness"),
    "powerlessness": ("negative", "powerlessness"),
    "helpless": ("negative", "helplessness"),
    "frustrated": ("negative", "frustration"),
    "frustration": ("negative", "frustration"),
    "exhausted": ("negative", "exhaustion"),
    "drained": ("negative", "exhaustion"),
    "depleted": ("negative", "exhaustion"),
    "lonely": ("negative", "loneliness"),
    "isolated": ("negative", "isolation"),
    "ashamed": ("negative", "shame"),
    "shame": ("negative", "shame"),
    "hurt": ("negative", "hurt"),
    "lost": ("negative", "uncertainty"),
    "uncertain": ("negative", "uncertainty"),
    "pressured": ("negative", "pressure"),
    "disconnected": ("negative", "alienation"),
    "crying": ("negative", "acute_sadness"),
    "numb": ("negative", "blunting"),
    "anxious": ("negative", "anxiety"),
    "stressed": ("negative", "stress"),
    "confused": ("negative", "confusion"),
    "sad": ("negative", "sadness"),
    "miss": ("negative", "longing"),
    "missing": ("negative", "longing"),
    "longing": ("negative", "longing"),
    "yearning": ("negative", "longing"),
    "heartbroken": ("negative", "heartbreak"),
    "heartbreak": ("negative", "heartbreak"),
    "grief": ("negative", "grief"),
    "mourning": ("negative", "grief"),
    "regret": ("negative", "regret"),
    "regretting": ("negative", "regret"),
    "loved": ("positive", "care/affection"),
    "love": ("positive", "care/affection"),
    "hollow": ("negative", "emptiness"),
    "dry": ("negative", "depletion"),
    "stuck": ("negative", "immobility"),
    "trapped": ("negative", "entrapment"),
    "empty": ("negative", "emptiness"),
    "bitter": ("negative", "resentment"),
    "defeated": ("negative", "defeat"),
    "panicked": ("negative", "panic"),
    "panic": ("negative", "panic"),
    "terrified": ("negative", "fear"),
    "insecure": ("negative", "insecurity"),
    "worthless": ("negative", "worthlessness"),
    "conflicted": ("negative", "ambivalence"),
    "torn": ("negative", "ambivalence"),
    "dread": ("negative", "dread"),
    "dreading": ("negative", "dread"),
    "resentful": ("negative", "resentment"),
    "burnout": ("negative", "burnout"),
    "froze": ("negative", "freeze"),
    "frozen": ("negative", "freeze"),
    "disposable": ("negative", "worthlessness"),
}


def _extract_stated_facts(doc, raw_text: str) -> List[StatedFact]:
    facts = []
    lowered = raw_text.lower()

    # 1. Actors from keywords and noun chunks
    for token in doc:
        w = token.lemma_.lower()
        if w in _ACTOR_KEYWORDS:
            span = token.text
            start = token.idx
            end = start + len(span)
            facts.append(StatedFact(
                text=span,
                category=_ACTOR_KEYWORDS[w],
                source_span=span,
                start_char=start,
                end_char=end,
            ))

    # 2. Key domain, milestone, and condition entities from keywords
    for chunk in doc.noun_chunks:
        chunk_text = chunk.text.strip()
        chunk_lower = chunk_text.lower()
        for kw, cat in _MILESTONE_KEYWORDS.items():
            if re.search(rf"\b{re.escape(kw)}\b", chunk_lower):
                start = chunk.start_char
                end = chunk.end_char
                facts.append(StatedFact(
                    text=chunk_text,
                    category=cat,
                    source_span=chunk_text,
                    start_char=start,
                    end_char=end,
                ))
                break

    # 3. Open Named Entities (spaCy doc.ents)
    for ent in doc.ents:
        ent_text = ent.text.strip()
        if ent.label_ in ("PERSON", "NORP") and not any(f.start_char == ent.start_char for f in facts):
            facts.append(StatedFact(
                text=ent_text,
                category="actor",
                source_span=ent_text,
                start_char=ent.start_char,
                end_char=ent.end_char,
            ))
        elif ent.label_ in ("MONEY", "PERCENT") and not any(f.start_char == ent.start_char for f in facts):
            facts.append(StatedFact(
                text=ent_text,
                category="obligation",
                source_span=ent_text,
                start_char=ent.start_char,
                end_char=ent.end_char,
            ))
        elif ent.label_ in ("EVENT",) and not any(f.start_char == ent.start_char for f in facts):
            facts.append(StatedFact(
                text=ent_text,
                category="event",
                source_span=ent_text,
                start_char=ent.start_char,
                end_char=ent.end_char,
            ))

    # 4. Open Noun Chunks for Situational Facts
    for chunk in doc.noun_chunks:
        c_text = chunk.text.strip()
        c_low = c_text.lower()
        # Skip pure pronouns
        if c_low in ("i", "me", "my", "myself", "it", "we", "us", "you", "they", "them", "he", "she", "him", "her", "this", "that"):
            continue
        if any(f.start_char == chunk.start_char for f in facts):
            continue

        # Classify meaningful noun phrases
        if any(w in c_low for w in ["rent", "tuition", "bill", "expense", "mortgage", "assignment", "work", "code", "task", "savings", "debt", "cash", "money", "loan"]):
            facts.append(StatedFact(text=c_text, category="obligation", source_span=c_text, start_char=chunk.start_char, end_char=chunk.end_char))
        elif any(w in c_low for w in ["canvas", "brushstroke", "paint", "art", "soccer", "sport", "game", "tryout", "rehab", "bakery", "business", "project", "store"]):
            facts.append(StatedFact(text=c_text, category="activity", source_span=c_text, start_char=chunk.start_char, end_char=chunk.end_char))
        elif any(w in c_low for w in ["acl", "crutch", "injury", "knee", "illness", "flare-up", "pain", "fatigue", "broken", "broke"]):
            facts.append(StatedFact(text=c_text, category="condition", source_span=c_text, start_char=chunk.start_char, end_char=chunk.end_char))
        elif any(w in c_low for w in ["partner", "professor", "teacher", "boss", "supervisor", "brother", "sister", "friend", "colleague", "cousin", "parent", "mother", "father", "mom", "dad", "roommate", "coworker", "landlord", "doctor"]):
            facts.append(StatedFact(text=c_text, category="actor", source_span=c_text, start_char=chunk.start_char, end_char=chunk.end_char))
        elif any(w in c_low for w in ["grade", "degree", "lead", "promotion", "milestone"]):
            facts.append(StatedFact(text=c_text, category="milestone", source_span=c_text, start_char=chunk.start_char, end_char=chunk.end_char))
        else:
            content_tokens = [tok for tok in chunk if not tok.is_stop and not tok.is_punct and len(tok.text) > 1]
            if content_tokens:
                cat = "actor" if any(tok.ent_type_ == "PERSON" for tok in chunk) else "domain"
                facts.append(StatedFact(
                    text=c_text,
                    category=cat,
                    source_span=c_text,
                    start_char=chunk.start_char,
                    end_char=chunk.end_char,
                ))

    event_patterns = [
        (r"\bfriends\s+(are\s+)?getting\s+placed\b", "event", "friends getting placed"),
        (r"\bdisappoint\s+(my\s+)?family\b", "stated_concern", "concern: disappointing family"),
        (r"\bautoimmune\s+flare-up\s+returned\b", "condition", "autoimmune flare-up returned"),
        (r"\bgave\s+credit\s+for\s+my\s+.*\s+project\b", "event", "supervisor gave credit to colleague"),
        (r"\bpromoted\s+to\s+lead\b", "milestone", "promoted to lead"),
        (r"\btaking\s+care\s+of\s+my\s+aging\s+mother\b", "event", "caregiving for aging mother"),
        (r"\bsnapped\s+at\s+her\b", "event", "snapped at mother"),
        (r"\bmanuscript\s+was\s+rejected\b", "event", "manuscript rejected"),
        (r"\bdinner\s+party\s+.*\s+didn'?t\s+invite\s+me\b", "event", "friends dinner party without invitation"),
        (r"\bsitting\s+on\s+the\s+floor\b", "behavioral_state", "sitting on floor"),
        (r"\bcan barely get out of bed\b", "physical_state", "unable to get out of bed"),
        (r"\b(drained\s+all\s+my\s+energy|completely\s+drained|exhausted)\b", "physical_state", "physical exhaustion"),
        (r"\b(paralyzed|unable\s+to\s+move)\b", "behavioral_state", "behavioral immobility"),
        (r"\bpriorities\s+(are\s+)?shifting(\s+every\s+now\s+and\s+then)?\b", "stated_concern", "shifting priorities"),
        (r"\bconfused\s+about\s+what\s+to\s+do\b", "stated_concern", "confusion about direction"),
        (r"\bwatching\s+(too\s+much\s+)?(content|videos|tv|shows|youtube|tiktok)\b", "behavioral_state", "excessive content consumption"),
        (r"\bto\s+numb\s+myself\b", "behavioral_state", "numbing coping behavior"),
        (r"\b(how\s+much\s+stuff\s+i\s+have\s+to\s+take\s+care\s+of|stuff\s+i\s+have\s+to\s+take\s+care\s+of)\b", "obligation", "multiple responsibilities to manage"),
        (r"\b(all\s+the\s+work\s+i\s+have\s+to\s+finish|work\s+i\s+have\s+to\s+finish)\b", "obligation", "workload to finish"),
        (r"\bi\s+don'?t\s+know\s+what\s+to\s+do\s+anymore\b", "stated_concern", "at a loss for direction"),
        (r"\b(miss(ing)?\s+(a\s+)?(person|someone|him|her|them|ex|my\s+ex))\b", "relational_state", "missing someone from past relationship"),
        (r"\b((he|she|they)\s+)?loved\s+me(\s+deeply)?\b", "relational_state", "other person loved the user deeply"),
        (r"\b(couldn'?t|unable\s+to|can'?t)\s+reciprocate\b", "relational_state", "inability to reciprocate romantic feelings"),
        (r"\b(want(ing)?\s+to\s+(reconnect|reach\s+out|talk\s+to\s+(him|her|them)|get\s+back(\s+together)?))\b", "stated_intent", "desire to reconnect"),
        (r"\b(don'?t\s+want\s+to|not\s+wanting\s+to)\s+(reconnect|resume|get\s+back(\s+together)?|reach\s+out)\b", "stated_boundary", "boundary against resuming relationship"),
        (r"\b(rent\s+went\s+up(\s+by\s+\d+%)?)\b", "obligation", "rent increase obligation"),
        (r"\b(brother\s+needs\s+tuition(\s+help)?)\b", "obligation", "brother tuition need"),
        (r"\b(skipping\s+meals)\b", "condition", "skipping meals for financial coping"),
        (r"\b(tore\s+(my\s+)?acl)\b", "condition", "torn ACL injury"),
        (r"\b(senior\s+season\s+tryouts)\b", "milestone", "senior season tryouts"),
        (r"\b(stuck\s+on\s+crutches)\b", "condition", "stuck on crutches"),
        (r"\b(partners\s+went\s+(completely\s+)?mia)\b", "event", "group partners went MIA"),
        (r"\b(submitted\s+zero\s+code)\b", "event", "partners submitted zero code"),
        (r"\b(grade\s+will\s+be\s+shared\s+equally)\b", "event", "team grade shared equally"),
        (r"\b(staring\s+at\s+this\s+blank\s+canvas)\b", "activity", "staring at blank canvas"),
        (r"\b(every\s+brushstroke\s+feels\s+hollow)\b", "condition", "brushstrokes feel hollow"),
        (r"\b(well\s+is\s+(completely\s+)?dry)\b", "condition", "creative well is dry"),
    ]
    for pattern, cat, label in event_patterns:
        m = re.search(pattern, lowered)
        if m:
            span = raw_text[m.start():m.end()]
            facts.append(StatedFact(
                text=label,
                category=cat,
                source_span=span,
                start_char=m.start(),
                end_char=m.end(),
            ))

    # Deduplicate by start/end char
    seen = set()
    deduped = []
    for f in facts:
        key = (f.start_char, f.end_char)
        if key not in seen:
            seen.add(key)
            deduped.append(f)
    return deduped


def _extract_stated_emotions(doc, raw_text: str) -> List[StatedEmotion]:
    emotions = []
    lowered = raw_text.lower()

    for token in doc:
        lemma = token.lemma_.lower()
        word = token.text.lower()
        key = word if word in _EMOTION_LEXICON else (lemma if lemma in _EMOTION_LEXICON else None)

        if key:
            valence, label = _EMOTION_LEXICON[key]
            start = token.idx
            end = start + len(token.text)
            target = None

            # Look for syntactic target (e.g. "worried about career", "scared that...")
            for child in token.children:
                if child.dep_ in ("prep", "ccomp", "dobj"):
                    target_span = raw_text[child.idx:child.idx + len(child.subtree_text) if hasattr(child, "subtree_text") else child.idx + 25]
                    target = target_span.strip()
                    break

            emotions.append(StatedEmotion(
                emotion_word=token.text,
                valence=valence,
                target=target,
                source_span=token.sent.text.strip() if token.sent else token.text,
                start_char=start,
                end_char=end,
            ))

    # Also detect copula and feeling complements (e.g. "feels hollow", "am stuck")
    for token in doc:
        if token.lemma_ in ("feel", "be", "seem") or token.dep_ in ("acomp", "attr"):
            for child in token.children:
                w = child.text.lower()
                lem = child.lemma_.lower()
                key = w if w in _EMOTION_LEXICON else (lem if lem in _EMOTION_LEXICON else None)
                if key and not any(e.start_char == child.idx for e in emotions):
                    valence, label = _EMOTION_LEXICON[key]
                    emotions.append(StatedEmotion(
                        emotion_word=child.text,
                        valence=valence,
                        target=None,
                        source_span=token.sent.text.strip() if token.sent else child.text,
                        start_char=child.idx,
                        end_char=child.idx + len(child.text),
                    ))

    # Deduplicate
    seen = set()
    deduped = []
    for e in emotions:
        key = (e.start_char, e.end_char)
        if key not in seen:
            seen.add(key)
            deduped.append(e)
    return deduped


def _extract_stated_behaviors(doc, raw_text: str) -> List[str]:
    """Extracts explicit actions, behavioral states, and coping habits."""
    behaviors = []
    lowered = raw_text.lower()
    patterns = [
        (r"\bwatching\s+(too\s+much\s+)?(content|videos|tv|shows|youtube|tiktok|reels|movies)\b", "excessive content consumption"),
        (r"\b(to\s+numb\s+myself|numb(ing)?\s+myself)\b", "numbing coping behavior"),
        (r"\b(sitting\s+on\s+the\s+floor|staring\s+at\s+(my\s+)?phone|unable\s+to\s+move)\b", "behavioral immobility / task freeze"),
        (r"\b(can\s+barely\s+get\s+out\s+of\s+bed|staying\s+in\s+bed)\b", "physical immobility in bed"),
        (r"\b(snapped\s+at\s+(her|him|them|my\s+mother|my\s+mom|parents))\b", "snapped at family member under strain"),
        (r"\b(crying(\s+all\s+morning)?)\b", "crying"),
        (r"\b(taking\s+care\s+of\s+my\s+aging\s+mother|caregiving)\b", "caregiving for aging mother"),
        (r"\b(working\s+full\s+time)\b", "working full time"),
        (r"\b(reading\s+(the\s+)?environmental\s+report)\b", "reading distressing report"),
        (r"\b(staring\s+at\s+(this\s+)?(blank\s+)?canvas)\b", "staring at blank canvas"),
        (r"\b(skipping\s+meals)\b", "skipping meals to cope with financial strain"),
        (r"\b(stuck\s+on\s+crutches)\b", "stuck on crutches"),
        (r"\b(watching\s+everyone\s+else\s+play)\b", "watching peers play from sidelines"),
        (r"\b(partners\s+went\s+(completely\s+)?mia)\b", "group partners went MIA"),
        (r"\b(submitted\s+zero\s+code)\b", "group partners submitted zero code"),
    ]
    for pat, desc in patterns:
        if re.search(pat, lowered) and desc not in behaviors:
            behaviors.append(desc)
    return behaviors


def _extract_stated_thoughts(doc, raw_text: str) -> List[StatedThoughtOrClaim]:
    thoughts = []
    lowered = raw_text.lower()

    thought_patterns = [
        r"\bi\s+haven'?t\s+done\s+enough\b",
        r"\bi'?ll\s+disappoint\s+(my\s+)?family\b",
        r"\bi\s+can'?t\s+be\s+productive\b",
        r"\bcan barely get out of bed\b",
        r"\bi\s+feel\s+completely\s+powerless\b",
        r"\bi\s+don'?t\s+know\s+whether\s+to\s+try\s+harder\s+or\s+let\s+go\b",
        r"\bi\s+feel\s+like\s+an?\s+(absolute\s+)?fraud\b",
        r"\bthey\s+will\s+realize\s+i\s+have\s+no\s+idea\b",
        r"\bi\s+feel\s+like\s+an\s+awful\s+person\b",
        r"\bwhat'?s\s+the\s+point\s+of\s+planning\b",
        r"\bplanet\s+is\s+burning\b",
        r"\bi\s+simply\s+have\s+no\s+talent\b",
        r"\bwasted\s+years\s+of\s+my\s+life\b",
        r"\bwondering\s+what'?s\s+wrong\s+with\s+me\b",
        r"\bunable\s+to\s+move\b",
        r"\b(i'?m\s+)?(really\s+)?confused\s+about\s+what\s+to\s+do\b",
        r"\b(my\s+)?priorities\s+are\s+shifting(\s+every\s+now\s+and\s+then)?\b",
        r"\bhow\s+much\s+stuff\s+i\s+have\s+to\s+take\s+care\s+of\b",
        r"\ball\s+the\s+work\s+i\s+have\s+to\s+finish\b",
        r"\bi\s+don'?t\s+know\s+what\s+to\s+do\s+anymore\b",
        r"\bto\s+numb\s+myself\b",
        r"\b(i\s+)?couldn'?t\s+reciprocate\b",
        r"\b(he|she|they)\s+loved\s+me(\s+deeply)?\b",
        r"\bi\s+miss\s+(a\s+)?(person|someone|him|her)\b",
        r"\b(i\s+)?(really\s+)?want\s+to\s+(reconnect|reach\s+out)\b",
        r"\b(i\s+)?(definitely\s+)?don'?t\s+want\s+to\s+(resume|get\s+back|reconnect)\b",
        r"\bi\s+don'?t\s+know\s+what\s+i\s+feel\b",
        r"\b[a-z\s]+\s+was\s+my\s+entire\s+identity\b",
        r"\bevery\s+brushstroke\s+feels\s+hollow\b",
        r"\b(the\s+)?well\s+is\s+(completely\s+)?dry\b",
        r"\bused\s+to\s+have\s+something\s+to\s+say\b",
        r"\bto\s+keep\s+everything\s+afloat\b",
        r"\bgrade\s+will\s+be\s+shared\s+equally\b",
        r"\bi\s+feel\s+disposable\b",
        r"\bnever\s+find\s+comparable\s+work\b",
        r"\b(committee\s+)?made\s+a\s+clerical\s+error\b",
    ]

    for pat in thought_patterns:
        m = re.search(pat, lowered)
        if m:
            span = raw_text[m.start():m.end()]
            thoughts.append(StatedThoughtOrClaim(
                statement=span,
                source_span=span,
                start_char=m.start(),
                end_char=m.end(),
            ))

    # Open cognitive verb complements
    for token in doc:
        if token.lemma_ in ("think", "feel", "worry", "fear", "wonder", "realize", "believe", "doubt", "assume") and token.dep_ in ("ROOT", "conj", "advcl"):
            for child in token.children:
                if child.dep_ in ("ccomp", "xcomp"):
                    start = child.idx
                    end = token.sent.end_char if token.sent else child.idx + 40
                    span_text = raw_text[start:end].strip()
                    if len(span_text) > 8 and not any(t.start_char == start for t in thoughts):
                        thoughts.append(StatedThoughtOrClaim(
                            statement=span_text,
                            source_span=span_text,
                            start_char=start,
                            end_char=start + len(span_text),
                        ))

    # Deduplicate
    seen = set()
    deduped = []
    for t in thoughts:
        key = (t.start_char, t.end_char)
        if key not in seen:
            seen.add(key)
            deduped.append(t)
    return deduped


# =============================================================================
# 3. MULTI-DIMENSIONAL APPRAISAL HEURISTICS (Marked Explicitly as Hypotheses)
# =============================================================================

def _infer_appraisals(
    raw_text: str,
    facts: List[StatedFact],
    emotions: List[StatedEmotion],
    thoughts: List[StatedThoughtOrClaim],
) -> Tuple[List[InferredAppraisal], List[str]]:
    appraisals = []
    concerns = []
    lowered = raw_text.lower()

    # 1. Social Comparison & Peer Pacing
    if re.search(r"\b(friends|peers|colleagues|coworkers|everyone(\s+else)?)\b.*\b(placed|succeeding|doing better|invite|dinner|pivoting|articulate|accomplished|ahead)\b", lowered) or \
       re.search(r"\bkeep\s+up\s+with\s+(my\s+)?peers\b", lowered):
        evidence = [f.source_span for f in facts if f.category in ("actor", "event") and any(w in f.source_span.lower() for w in ["friends", "peers", "placed", "invite", "coworkers", "everyone"])]
        if not evidence:
            m = re.search(r"\b(friends|peers|colleagues|coworkers|everyone(\s+else)?)[^.?!]*\b", lowered)
            evidence = [raw_text[m.start():m.end()].strip()] if m else ["Mention of peer pacing or social circle"]
        appraisals.append(InferredAppraisal(
            dimension="social_comparison",
            interpretation="Evaluation of personal pacing against observed peer progress or social inclusion.",
            confidence=0.85,
            evidence_spans=evidence,
            reasoning="User references external peers and compares personal status or involvement.",
        ))
        concerns.append("peer_comparison_and_pacing")

    # 2. Career Horizon / Future Transition
    if re.search(r"\b(career\s+(path|transition|uncertainty|horizon|future|choice)|after\s+graduation|graduat(e|ing)\s+soon|finding\s+a\s+job|job\s+hunt(ing)?|job\s+market|getting\s+placed|unemployed|worried\s+about\s+(my\s+)?career|phased\s+out|disposable|find\s+(comparable\s+)?work|never\s+find\s+(comparable\s+)?work|layoff)\b", lowered) or \
       (re.search(r"\b(career|placement)\b", lowered) and re.search(r"\b(anxious|worried|stress|uncertain|dread)\b", lowered)):
        evidence = [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["career", "graduation", "job", "placed", "promotion", "unit", "work", "ai"])]
        if not evidence:
            m = re.search(r"\b(career|graduation|future|phased out|work)[^.?!]*\b", lowered)
            evidence = [raw_text[m.start():m.end()].strip()] if m else ["Career or future transition referenced"]
        appraisals.append(InferredAppraisal(
            dimension="career_horizon_uncertainty",
            interpretation="Anticipatory concern regarding professional transition and upcoming milestones.",
            confidence=0.88,
            evidence_spans=evidence,
            reasoning="User identifies a major impending transition into the workforce or professional role.",
        ))
        concerns.append("career_transition_uncertainty")

    # 3. Filial / Interpersonal Expectation Pressure & Boundary Guilt
    if re.search(r"\b(disappoint\s+(my\s+)?(family|parents|mother|father|mom|dad))\b", lowered) or \
       re.search(r"\b(aging\s+mother|snapped\s+at\s+her)\b", lowered) or \
       re.search(r"\b(awful|bad|terrible|guilty|ungrateful)\s+(daughter|son|child)\b", lowered) or \
       re.search(r"\b(mother|father|mom|dad|parents?)\s+(expects?|demands?|makes?\s+me\s+feel|guilt(s|ing)?)\b", lowered) or \
       re.search(r"\b(say\s+no|boundary|boundaries)\b.*\b(mother|father|mom|dad|family|parents?)\b", lowered):
        evidence = [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["family", "mother", "father", "daughter", "son", "parent", "chores", "visit", "weekend"])] or ["Family expectation pressure and boundary guilt"]
        appraisals.append(InferredAppraisal(
            dimension="evaluation_fear",
            interpretation="Concern regarding parental expectations, filial guilt, or setting interpersonal boundaries with family.",
            confidence=0.88,
            evidence_spans=evidence,
            reasoning="User articulates intense guilt or pressure balancing familial demands with personal capacity and boundaries.",
        ))
        concerns.append("family_boundary_pressure")

    # 4. Perceived Self-Deficit
    if re.search(r"\b(haven'?t\s+done\s+enough|can'?t\s+be\s+productive|no\s+talent|awful\s+person|fraud|what'?s\s+wrong\s+with\s+me|clerical\s+error|mistake\s+admitting|don'?t\s+belong)\b", lowered):
        evidence = [t.statement for t in thoughts if any(w in t.statement.lower() for w in ["enough", "productive", "talent", "awful", "fraud", "wrong", "clerical", "error"])] or ["Perceived personal inadequacy or imposter fear"]
        appraisals.append(InferredAppraisal(
            dimension="perceived_deficit",
            interpretation="Internalized self-evaluation attributing difficulty to personal inadequacy or insufficient effort.",
            confidence=0.80,
            evidence_spans=evidence,
            reasoning="User verbalizes a feeling of falling short, being inadequate, or lacking necessary output.",
        ))
        concerns.append("self_deficit_evaluation")

    # 5. External Workplace Injustice / Powerlessness
    if re.search(r"\b(supervisor|boss|manager)\b.*\b(credit|stole|took|unfair)\b", lowered) or \
       re.search(r"\bfeel(ing)?\s+completely\s+powerless\b", lowered):
        evidence = [f.source_span for f in facts if "supervisor" in f.source_span.lower()] or ["Feeling powerless over workplace action"]
        appraisals.append(InferredAppraisal(
            dimension="systemic_injustice",
            interpretation="Experience of unacknowledged labor or unaddressed institutional unfairness.",
            confidence=0.90,
            evidence_spans=evidence,
            reasoning="User describes an external violation of professional fairness by authority figure.",
        ))
        concerns.append("workplace_injustice")

    # 6. Physical Illness / Bodily Limitation
    if re.search(r"\b(autoimmune|flare-up|sick|bed|chronic|illness|pain)\b", lowered):
        evidence = [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["flare-up", "autoimmune", "bed"])]
        appraisals.append(InferredAppraisal(
            dimension="bodily_limitation",
            interpretation="Legitimate physiological depletion or health flare-up restricting physical capacity.",
            confidence=0.92,
            evidence_spans=evidence,
            reasoning="User explicitly identifies biological symptoms preventing physical activity.",
        ))
        concerns.append("bodily_illness_constraint")

    # 7. Executive Dysfunction / Behavioral Paralysis
    if re.search(r"\b(assignments\s+due|laundry|fridge|sitting\s+on\s+the\s+floor|unable\s+to\s+move|four\s+hours)\b", lowered):
        evidence = [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["assignments", "laundry", "floor"])]
        appraisals.append(InferredAppraisal(
            dimension="executive_freeze",
            interpretation="Cognitive freeze / task accumulation resulting in behavioral immobility.",
            confidence=0.88,
            evidence_spans=evidence,
            reasoning="User describes competing tasks coupled with several hours of physical immobility.",
        ))
        concerns.append("executive_freeze")

    # 8. Shifting Priorities / Direction Uncertainty
    if re.search(r"\b(priorities\s+(are\s+)?shifting|shifting\s+priorities|priorities\s+keep\s+shifting|shifting\s+every\s+now\s+and\s+then)\b", lowered) or ("priorit" in lowered and ("shift" in lowered or "confus" in lowered)):
        evidence = [f.source_span for f in facts if "priorit" in f.source_span.lower()] or ["priorities are shifting"]
        appraisals.append(InferredAppraisal(
            dimension="priority_reorientation",
            interpretation="Experiencing fluctuating priorities and uncertainty regarding current focus or next direction.",
            confidence=0.88,
            evidence_spans=evidence,
            reasoning="User explicitly articulates shifting priorities and confusion about what direction to take.",
        ))
        concerns.append("shifting_priorities_uncertainty")

    # 9. Emotional Overwhelm & Content Consumption / Escape (Case A)
    if re.search(r"\b(content|videos|tv|shows|youtube|scrolling|binging)\b.*\b(numb|distract|overwhelm)\b", lowered) or \
       (re.search(r"\bnumb\s+myself\b", lowered) and re.search(r"\b(overwhelm|stuff|tasks|work|responsibilities)\b", lowered)) or \
       (re.search(r"\bwatching\s+(too\s+much\s+)?content\b", lowered) and "numb" in lowered):
        evidence = ["watching too much content", "numb myself from the overwhelming feeling"]
        appraisals.append(InferredAppraisal(
            dimension="overwhelm_and_avoidance",
            interpretation="Content consumption appears to function as an attempt to find temporary relief or numbness from an overwhelming volume of competing responsibilities.",
            confidence=0.90,
            evidence_spans=evidence,
            reasoning="User describes turning to content consumption specifically to numb the feeling of having too much stuff to take care of.",
        ))
        concerns.append("overwhelm_and_coping_distraction")

    # 10. Workload Overwhelm (Case D)
    elif re.search(r"\b(overwhelmed|overwhelming)\b.*\b(work|tasks|stuff|finish|deadlines|assignments)\b", lowered) or \
         re.search(r"\b(all\s+the\s+work\s+i\s+have\s+to\s+finish)\b", lowered):
        evidence = ["overwhelmed by work that needs to be finished"]
        appraisals.append(InferredAppraisal(
            dimension="workload_overwhelm",
            interpretation="User is experiencing acute emotional overwhelm in response to accumulating work obligations that need to be completed.",
            confidence=0.86,
            evidence_spans=evidence,
            reasoning="User identifies a high volume of work and an emotional state of overwhelm.",
        ))
        concerns.append("workload_overwhelm")

    # 11. Relational Longing & Unreciprocated Feelings
    if (re.search(r"\bmiss\b", lowered) and re.search(r"\b(couldn'?t\s+reciprocate|unable\s+to\s+reciprocate|reciprocate)\b", lowered)) or \
       (re.search(r"\bmiss\b", lowered) and re.search(r"\bloved\s+me\b", lowered) and "reciprocate" in lowered):
        evidence = [f.source_span for f in facts if f.category == "relational_state" or "person" in f.text.lower() or "partner" in f.text.lower()]
        if not evidence:
            evidence = ["missing someone who loved the user deeply", "inability to reciprocate feelings"]
        appraisals.append(InferredAppraisal(
            dimension="unreciprocated_relational_longing",
            interpretation="Experiencing longing or bittersweet reflection for someone from the past who cared deeply, while holding the reality that feelings could not be reciprocated.",
            confidence=0.90,
            evidence_spans=evidence,
            reasoning="User identifies missing a person who loved them deeply alongside an inability to reciprocate.",
        ))
        concerns.append("unreciprocated_relational_longing")
    elif re.search(r"\bmiss\b", lowered) and (re.search(r"\b(want\s+to\s+reconnect|really\s+want\s+to\s+(reach\s+out|reconnect)|reach\s+out\s+and\s+reconnect)\b", lowered) or "want to reconnect" in lowered):
        evidence = ["missing someone and considering reconnecting"]
        appraisals.append(InferredAppraisal(
            dimension="relational_longing_reconnection",
            interpretation="Experiencing longing for a past person with an active consideration or desire to reach out and reconnect.",
            confidence=0.88,
            evidence_spans=evidence,
            reasoning="User expresses missing someone accompanied by a desire to reconnect.",
        ))
        concerns.append("relational_longing_reconnection")
    elif re.search(r"\bmiss\b", lowered) and (re.search(r"\b(don'?t\s+want\s+to\s+(resume|reconnect|get\s+back)|not\s+wanting\s+to\s+resume|do\s+not\s+want\s+to\s+resume)\b", lowered)):
        evidence = ["missing someone while maintaining boundary against resuming relationship"]
        appraisals.append(InferredAppraisal(
            dimension="relational_longing_with_boundary",
            interpretation="Experiencing genuine longing or grief for a past person while holding a clear personal boundary not to resume the relationship.",
            confidence=0.90,
            evidence_spans=evidence,
            reasoning="User acknowledges missing someone while explicitly choosing not to resume the relationship.",
        ))
        concerns.append("relational_longing_with_boundary")

    # 12. Academic / Collaboration Injustice (Group Project MIA / Shared Grade)
    if re.search(r"\b(group\s+project|partners\s+went\s+(completely\s+)?mia|zero\s+code|grade\s+will\s+be\s+shared)\b", lowered) and "systemic_injustice" not in [a.dimension for a in appraisals]:
        evidence = [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["partners", "code", "grade", "project"])] or ["Group project partners went MIA and shared grading policy"]
        appraisals.append(InferredAppraisal(
            dimension="systemic_injustice",
            interpretation="Bearing the burden of uncooperative project team partners while subject to an unfair shared grading policy.",
            confidence=0.90,
            evidence_spans=evidence,
            reasoning="User describes carrying project work alone and facing an institutional grading policy that rewards uninvolved peers.",
        ))
        concerns.append("collaboration_injustice")

    # 13. Physical Injury / Sports Identity Disruption
    if re.search(r"\b(acl|knee\s+injury|torn\s+acl|crutches|senior\s+season\s+tryouts)\b", lowered) and "bodily_limitation" not in [a.dimension for a in appraisals]:
        evidence = [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["acl", "crutches", "tryouts", "soccer"])] or ["Physical injury and athletic displacement"]
        appraisals.append(InferredAppraisal(
            dimension="bodily_limitation",
            interpretation="Acute physical injury sidelining participation in sports and disrupting primary athletic identity.",
            confidence=0.92,
            evidence_spans=evidence,
            reasoning="User identifies a torn ACL and mobility restriction right before competitive tryouts.",
        ))
        concerns.append("physical_injury_constraint")

    # 14. Resource Strain & Escalating Living Obligations
    if re.search(r"\b(rent\s+went\s+up|tuition|skipping\s+meals|keep\s+everything\s+afloat)\b", lowered):
        evidence = [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["rent", "tuition", "meals", "brother"])] or ["Financial cost escalation and meal-skipping sacrifices"]
        appraisals.append(InferredAppraisal(
            dimension="resource_strain_uncertainty",
            interpretation="Experiencing acute pressure from sudden financial demands and personal physical sacrifices to support family and maintain housing.",
            confidence=0.88,
            evidence_spans=evidence,
            reasoning="User articulates steep rent increase, sibling tuition support, and meal-skipping coping.",
        ))
        concerns.append("resource_strain_uncertainty")

    # 15. Creative Block & Expressive Depletion
    if re.search(r"\b(blank\s+canvas|brushstroke\s+feels\s+hollow|well\s+is\s+(completely\s+)?dry)\b", lowered):
        evidence = [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["canvas", "brushstroke", "well"])] or ["Prolonged creative block and expressive depletion"]
        appraisals.append(InferredAppraisal(
            dimension="creative_block",
            interpretation="Experiencing expressive exhaustion and self-doubt after prolonged effort at the canvas.",
            confidence=0.88,
            evidence_spans=evidence,
            reasoning="User articulates staring at a blank canvas and experiencing creative expression as hollow.",
        ))
        concerns.append("creative_drought")

    return appraisals, concerns


def _infer_uncertainty(raw_text: str, appraisals: List[InferredAppraisal]) -> UncertaintyProfile:
    lowered = raw_text.lower()
    dims = {a.dimension for a in appraisals}

    # Relational longing & unreciprocated care / boundary
    if "unreciprocated_relational_longing" in dims or "relational_longing_reconnection" in dims or "relational_longing_with_boundary" in dims:
        return UncertaintyProfile(
            has_uncertainty=True,
            uncertainty_type="relational_longing_uncertainty",
            is_inherently_unpredictable=True,
            preservation_required=True,
            evidence_spans=["miss a person", "couldn't reciprocate"] if "reciprocate" in lowered else ["missing someone"],
        )

    # Relational ambivalence
    if re.search(r"\b(don'?t\s+know\s+whether\s+to\s+try\s+harder\s+or\s+let\s+go|try\s+harder\s+or\s+let\s+go)\b", lowered) or \
       (re.search(r"\b(dating|relationship)\b", lowered) and "disconnected" in lowered):
        return UncertaintyProfile(
            has_uncertainty=True,
            uncertainty_type="relational_ambivalence",
            is_inherently_unpredictable=True,
            preservation_required=True,
            evidence_spans=["I don't know whether to try harder or let go"] if "try harder" in lowered else ["emotionally disconnected"],
        )

    # Climate / Macro existential
    if re.search(r"\b(planet\s+is\s+burning|hopeless\s+about\s+the\s+future|environmental\s+report)\b", lowered):
        return UncertaintyProfile(
            has_uncertainty=True,
            uncertainty_type="macro_existential",
            is_inherently_unpredictable=True,
            preservation_required=True,
            evidence_spans=["hopeless about the future", "planet is burning"],
        )

    # Shifting priorities / Direction uncertainty
    if "priority_reorientation" in dims or re.search(r"\b(priorities\s+(are\s+)?shifting|shifting\s+priorities|priorities\s+keep\s+shifting)\b", lowered) or ("priorit" in lowered and ("shift" in lowered or "confus" in lowered)):
        return UncertaintyProfile(
            has_uncertainty=True,
            uncertainty_type="priority_uncertainty",
            is_inherently_unpredictable=False,
            preservation_required=True,
            evidence_spans=["confused about what to do", "priorities are shifting"],
        )

    # Future outcome / Career horizon
    if "career_horizon_uncertainty" in dims or re.search(r"\b(future|career|after graduation|what will happen)\b", lowered):
        return UncertaintyProfile(
            has_uncertainty=True,
            uncertainty_type="future_outcome",
            is_inherently_unpredictable=True,
            preservation_required=True,
            evidence_spans=["worried about my career after graduation"] if "career" in lowered else ["future"],
        )

    return UncertaintyProfile(has_uncertainty=False)


def _infer_controllability(facts: List[StatedFact], appraisals: List[InferredAppraisal]) -> ControllabilityAnalysis:
    dims = {a.dimension for a in appraisals}
    controllable = []
    uncontrollable = []

    if "career_horizon_uncertainty" in dims:
        controllable.append("Individual job applications, interview preparation, and personal daily pacing")
        uncontrollable.append("Macro hiring market timelines and specific employer decision schedules")

    if "social_comparison" in dims:
        uncontrollable.append("Other people's timelines, placements, and milestones")
        controllable.append("Focusing attention on personal growth and self-chosen criteria")

    if "evaluation_fear" in dims:
        facts_text = " ".join(f.text.lower() for f in facts)
        if any(w in facts_text for w in ["mother", "father", "mom", "dad", "parents", "daughter", "son", "visit", "weekend"]):
            controllable.append("Deciding how to allocate your personal rest time, and communicating your capacity boundaries honestly")
            uncontrollable.append("Your family members' expectations, and how they react emotionally when you say no")
        else:
            uncontrollable.append("Family members' immediate emotional reactions or unspoken expectations")
            controllable.append("Communicating honestly about one's efforts and setting compassionate boundaries")

    if "systemic_injustice" in dims:
        if any(w in f.text.lower() for f in facts for w in ["partner", "grade", "mia", "zero code"]):
            controllable.append("Documenting individual project contributions and commit records, and requesting a constructive meeting with the professor")
            uncontrollable.append("Whether project partners choose to do their share, and the professor's shared grading policy")
        else:
            uncontrollable.append("Supervisor's past behavior during the meeting")
            controllable.append("Documenting work, speaking with HR/mentors, or establishing project boundaries")

    if "bodily_limitation" in dims:
        if any(w in f.text.lower() for f in facts for w in ["acl", "crutch", "injury", "tryout", "soccer"]):
            controllable.append("Following physical rehabilitation guidelines, honoring your body's healing pace, and staying connected to teammates from the sidelines")
            uncontrollable.append("The physical injury having occurred, and the biological timeline required for tissues to heal")
        else:
            uncontrollable.append("Biological flare-up and involuntary physical exhaustion")
            controllable.append("Permitting restful recovery and hydration without self-blame")

    if "resource_strain_uncertainty" in dims:
        controllable.append("Prioritizing regular physical meals and restful recovery, and taking one immediate expense or support contact at a time")
        uncontrollable.append("External inflation, sudden rent price increases, and having to solve the entire financial future all at once")

    if "creative_block" in dims:
        controllable.append("Allowing yourself to step away from the canvas for restorative rest, engaging in low-stakes play, and detaching your creative worth from immediate output")
        uncontrollable.append("Forcing spontaneous creative inspiration or artistic flow to strike on command")

    if "executive_freeze" in dims:
        controllable.append("Selecting a single 2-minute entry task (e.g. drinking water, clearing one item)")
        uncontrollable.append("Completing all assignments and household chores all at once")

    if "priority_reorientation" in dims:
        controllable.append("Choosing one small, immediate focus for today and allowing longer-term priorities to clarify gradually")
        uncontrollable.append("Having all future priorities permanently fixed or resolved all at once")

    if "overwhelm_and_avoidance" in dims:
        controllable.append("Choosing one single responsibility to look at first, or giving yourself a structured, guilt-free pause before returning to tasks")
        uncontrollable.append("The total accumulated volume of things you have to take care of all at once")

    if "workload_overwhelm" in dims:
        controllable.append("Selecting just one single task or item to start with, and taking intentional pacing pauses")
        uncontrollable.append("The total volume of pending work all at once")

    if "unreciprocated_relational_longing" in dims:
        controllable.append("Honoring your authentic emotional capacity, and deciding how to hold space for these memories without self-blame")
        uncontrollable.append("The past reality of their deep feelings and your inability to force feelings that weren't there")

    if "relational_longing_reconnection" in dims:
        controllable.append("Reflecting thoughtfully on your true intentions, and choosing whether and how to reach out with respect for both parties' boundaries")
        uncontrollable.append("How the other person might respond, and whether their feelings or circumstances have changed over time")

    if "relational_longing_with_boundary" in dims:
        controllable.append("Honoring your decision not to resume the relationship, and giving yourself permission to mourn the loss without having to reverse your boundary")
        uncontrollable.append("Experiencing spontaneous waves of sadness, nostalgia, or missing the connection")

    # Dynamic fallback: context-grounded when facts exist, gentle pause when sparse
    if not controllable and not uncontrollable:
        if facts:
            context_topics = ", ".join(dict.fromkeys([f.text for f in facts[:2] if f.text]))
            if context_topics:
                controllable.append(f"Choosing how you allocate your energy today, honoring your immediate boundaries, and taking one steady step regarding {context_topics}")
                uncontrollable.append(f"Past occurrences around {context_topics} that have already happened, and the unpredictable choices or reactions of other people")
            else:
                controllable.append("Choosing how you allocate your energy today, honoring your immediate boundaries, and taking one steady, manageable step at a time")
                uncontrollable.append("Past occurrences that have already happened, and the unpredictable choices or reactions of other people")
        else:
            controllable.append("Taking a slow pause right now, catching your breath, and choosing whether you wish to explore this further or just rest")
            uncontrollable.append("Needing to immediately figure out every feeling, next step, or answer right this second")

    return ControllabilityAnalysis(
        potentially_controllable=controllable,
        potentially_uncontrollable=uncontrollable,
        confidence=0.75 if (controllable or uncontrollable) else 0.3,
    )


def _infer_support_needs(
    appraisals: List[InferredAppraisal],
    uncertainty: UncertaintyProfile,
) -> SupportNeedsHypothesis:
    dims = {a.dimension for a in appraisals}
    possible_needs = []
    contraindications = []

    if "bodily_limitation" in dims:
        possible_needs.append("empathetic_validation")
        possible_needs.append("permission_to_rest")
        contraindications.append("do_not_frame_physical_illness_as_cognitive_distortion")
        contraindications.append("do_not_demand_productivity_steps")

    if "systemic_injustice" in dims:
        possible_needs.append("validation_of_injustice")
        possible_needs.append("boundary_and_objective_options")
        contraindications.append("do_not_gaslight_or_reframe_supervisor_behavior")

    if "resource_strain_uncertainty" in dims:
        possible_needs.append("compassionate_pacing_and_nourishment")
        possible_needs.append("practical_resource_identification")
        contraindications.append("do_not_minimize_real_financial_hardship")
        contraindications.append("do_not_demand_instant_long_term_financial_solutions")

    if "creative_block" in dims:
        possible_needs.append("normalizing_creative_cycles")
        possible_needs.append("rest_and_low_stakes_play")
        contraindications.append("do_not_force_immediate_artistic_production")
        contraindications.append("do_not_frame_creative_rest_as_laziness")

    if uncertainty.uncertainty_type == "relational_ambivalence":
        possible_needs.append("holding_space_for_ambivalence")
        possible_needs.append("reflective_clarification")
        contraindications.append("do_not_force_premature_decision_or_false_certainty")

    if uncertainty.uncertainty_type == "priority_uncertainty" or "priority_reorientation" in dims:
        possible_needs.append("values_clarification_and_grounding")
        possible_needs.append("permission_to_hold_flux")
        contraindications.append("do_not_assume_trauma_or_relationship_conflict")
        contraindications.append("do_not_force_premature_rigid_plan")

    if "overwhelm_and_avoidance" in dims:
        possible_needs.append("empathetic_validation")
        possible_needs.append("gentle_single_task_prioritization")
        contraindications.append("do_not_label_as_lazy_or_addicted")
        contraindications.append("do_not_demand_completing_all_tasks_at_once")
        contraindications.append("do_not_pathologize_coping_behavior")

    if "workload_overwhelm" in dims:
        possible_needs.append("task_structuring_and_pacing")
        contraindications.append("do_not_overwhelm_with_multi_step_planning")
        contraindications.append("do_not_frame_workload_as_personal_inadequacy")

    if "unreciprocated_relational_longing" in dims:
        possible_needs.append("empathetic_holding_space")
        possible_needs.append("reflective_clarification")
        contraindications.append("do_not_assume_reconciliation_intent")
        contraindications.append("do_not_assume_unresolved_trauma_or_pathology")
        contraindications.append("do_not_impose_guilt_or_self_blame_for_unreciprocated_feelings")
        contraindications.append("do_not_diagnose_attachment_pattern")

    if "relational_longing_reconnection" in dims:
        possible_needs.append("thoughtful_intention_clarification")
        contraindications.append("do_not_guarantee_positive_response_from_other_person")
        contraindications.append("do_not_rush_into_impulsive_contact")

    if "relational_longing_with_boundary" in dims:
        possible_needs.append("validation_of_grief_alongside_boundary")
        contraindications.append("do_not_treat_missing_them_as_a_reason_to_break_boundary")
        contraindications.append("do_not_invalidate_past_feelings")

    if "social_comparison" in dims and "career_horizon_uncertainty" in dims:
        possible_needs.append("values_clarification_and_pacing_differentiation")
        possible_needs.append("decoupling_self_worth_from_peer_timeline")
        contraindications.append("do_not_dismiss_family_concern_as_irrational")

    if "executive_freeze" in dims:
        possible_needs.append("somatic_grounding_and_micro_step")
        contraindications.append("do_not_overwhelm_with_multi_step_planning")

    return SupportNeedsHypothesis(
        possible_needs=possible_needs or ["open_reflective_exploration"],
        contraindications=contraindications,
    )


def _identify_unknowns(
    raw_text: str,
    facts: List[StatedFact],
    emotions: List[StatedEmotion],
    thoughts: List[StatedThoughtOrClaim],
    appraisals: List[InferredAppraisal],
) -> UnknownOrUnstatedInfo:
    dims = {a.dimension for a in appraisals}
    missing = []

    if "career_horizon_uncertainty" in dims:
        missing.append("Specific career field, target roles, or active applications")
        missing.append("What 'doing enough' specifically means to the user")

    if "evaluation_fear" in dims:
        missing.append("Family's actual stated expectations vs. internal anticipated dread")

    if "social_comparison" in dims:
        missing.append("User's own personal criteria for success independent of friends")

    if "bodily_limitation" in dims:
        missing.append("Current medical guidance or accommodation options")

    if "systemic_injustice" in dims:
        missing.append("Supervisor's actual intent vs. observable action")
        missing.append("Colleague's role in the attribution")
        missing.append("Workplace reporting structures or written documentation of project authorship")

    if "priority_reorientation" in dims:
        missing.append("What the specific competing priorities are")
        missing.append("What is causing the priorities to fluctuate")
        missing.append("Whether the user is distressed by the change or simply seeking practical clarity")

    if "overwhelm_and_avoidance" in dims:
        missing.append("Which specific responsibilities or tasks are pressing most")
        missing.append("How long the content consumption pattern has continued")
        missing.append("What kind of immediate relief or practical support feels most accessible")

    if "workload_overwhelm" in dims:
        missing.append("Specific nature and deadlines of the pending work items")
        missing.append("Whether tasks can be delegated, postponed, or segmented")

    if "unreciprocated_relational_longing" in dims:
        missing.append("Whether the user wishes to reach out, find peace with moving on, or simply process the grief of missing them")
        missing.append("How much time has passed since the connection was active")

    if not facts:
        missing.append("Concrete situational trigger or context")

    missing.append("User's preferred support modality (listening vs. planning vs. perspective)")

    return UnknownOrUnstatedInfo(missing_aspects=missing)


def _extract_user_goal(raw_text: str, thoughts: List[StatedThoughtOrClaim]) -> Optional[str]:
    lowered = raw_text.lower()
    if re.search(r"\bto\s+numb\s+myself\b", lowered):
        return "seeking relief or distraction from overwhelming feelings"
    if re.search(r"\bto\s+keep\s+everything\s+afloat\b", lowered):
        return "striving to stay afloat financially and support family"
    if re.search(r"\b(confused\s+about\s+what\s+to\s+do|don'?t\s+know\s+what\s+to\s+do)\b", lowered):
        return "seeking clarity on immediate priorities and direction"
    if re.search(r"\b(work\s+i\s+have\s+to\s+finish|to\s+finish)\b", lowered):
        return "seeking to make progress on pending responsibilities"
    if re.search(r"\b(try\s+harder\s+or\s+let\s+go)\b", lowered):
        return "determining whether to reinvest in the relationship or let go"
    if re.search(r"\b(can'?t\s+be\s+productive|haven'?t\s+done\s+enough)\b", lowered):
        return "wishing to fulfill expectations and be productive"
    if re.search(r"\b(powerless|furious)\b", lowered):
        return "seeking validation and constructive boundaries after unfair treatment"
    if re.search(r"\b(want(ing)?\s+to\s+(reconnect|reach\s+out|talk\s+to\s+(him|her|them)|get\s+back))\b", lowered):
        return "considering reconnecting or reaching out"
    if re.search(r"\b(don'?t\s+want\s+to|not\s+wanting\s+to)\s+(resume|reconnect|get\s+back|reach\s+out)\b", lowered):
        return "maintaining personal boundaries against resuming the relationship"
    if re.search(r"\bmiss\b", lowered) and re.search(r"\b(reciprocate|loved\s+me)\b", lowered):
        return None  # The goal is unstated / unknown
    return None


def _extract_context(raw_text: str, facts: List[StatedFact], behaviors: List[str]) -> str:
    parts = []
    for f in facts:
        if f.category in ("event", "obligation", "condition", "milestone", "stated_concern", "relational_state", "stated_intent", "stated_boundary"):
            parts.append(f.text)
    if behaviors:
        parts.extend(behaviors)
    if parts:
        return "; ".join(parts[:3])
    return "general personal reflection"


def _extract_needs_or_concerns(
    facts: List[StatedFact],
    emotions: List[StatedEmotion],
    appraisals: List[InferredAppraisal],
    user_goal: Optional[str],
) -> List[str]:
    needs = []
    dims = {a.dimension for a in appraisals}
    if "overwhelm_and_avoidance" in dims:
        needs.append("relief from acute task overwhelm without guilt")
        needs.append("gentle single-task prioritization")
    elif "workload_overwhelm" in dims:
        needs.append("pacing and breaking down pending workload")
    if "systemic_injustice" in dims:
        needs.append("validation of unacknowledged labor")
        needs.append("objective options for self-advocacy or documentation")
    if "priority_reorientation" in dims:
        needs.append("grounding in immediate priorities without premature rigidity")
    if "bodily_limitation" in dims:
        needs.append("guilt-free permission to rest and recover")
    if "executive_freeze" in dims:
        needs.append("breaking task freeze through a tiny 2-minute entry step")
    if "resource_strain_uncertainty" in dims:
        needs.append("protecting basic physical nourishment while navigating financial obligations")
    if "creative_block" in dims:
        needs.append("normalizing creative rhythm and resting without self-blame")
    if "unreciprocated_relational_longing" in dims:
        needs.append("processing complex feelings of missing someone without guilt or forced closure")
    if "relational_longing_reconnection" in dims:
        needs.append("clarifying intentions and boundaries before reaching out")
    if "relational_longing_with_boundary" in dims:
        needs.append("allowing space for grief while preserving personal boundaries")
    if user_goal and user_goal not in needs:
        needs.append(user_goal)
    return needs or ["supportive reflection and open exploration"]


def _infer_tentative_interpretations(
    appraisals: List[InferredAppraisal],
    facts: List[StatedFact],
    emotions: List[StatedEmotion],
    behaviors: List[str],
) -> List[str]:
    interpretations = []
    for a in appraisals:
        if a.interpretation not in interpretations:
            interpretations.append(a.interpretation)
    return interpretations or ["The user is reflecting on an uncertain or stressful experience without establishing detailed circumstances."]


def _assess_ambiguity(
    raw_text: str,
    facts: List[StatedFact],
    emotions: List[StatedEmotion],
    thoughts: List[StatedThoughtOrClaim],
    behaviors: List[str],
    appraisals: List[InferredAppraisal],
    uncertainty: UncertaintyProfile,
) -> str:
    """
    Assesses input ambiguity based on what is actually present vs. missing.
    - 'sufficient': Has meaningful situation/context, stated facts, specific pattern, or multiple dimensions.
    - 'partial': Has an emotional state and a general source of distress (e.g. 'overwhelmed by all the work I have to finish').
    - 'sparse_insufficient': Lacks situational detail, trigger, and concrete object (e.g. 'I don't know what to do anymore').
    """
    dims = {a.dimension for a in appraisals}
    words = raw_text.split()

    # Truly sparse: very short input with no facts, no behaviors, and no active appraisals
    if len(words) <= 4 and not facts and not behaviors and not dims:
        return "sparse_insufficient"
    if re.search(r"\b(i\s+don'?t\s+know\s+what\s+to\s+do\s+anymore|i\s+don'?t\s+know\s+what\s+i\s+feel)\b", raw_text.lower()) and len(words) <= 8:
        return "sparse_insufficient"

    if any(d in dims for d in (
        "overwhelm_and_avoidance", "priority_reorientation", "systemic_injustice",
        "bodily_limitation", "executive_freeze", "workload_overwhelm",
        "unreciprocated_relational_longing", "relational_longing_reconnection",
        "relational_longing_with_boundary", "resource_strain_uncertainty", "creative_block"
    )):
        return "sufficient"
    if len(facts) >= 2 or len(behaviors) >= 1 or (len(facts) >= 1 and len(emotions) >= 1):
        return "sufficient"
    if len(words) > 10 and (len(facts) >= 1 or len(thoughts) >= 1):
        return "sufficient"
    if len(emotions) >= 1 and (len(thoughts) >= 1 or len(words) > 5):
        return "partial"
    return "sparse_insufficient"


# =============================================================================
# 4. PRIMARY EXTRACTION PIPELINE
# =============================================================================

def extract_case_representation(
    text: str,
    emotion_scores: Optional[Dict[str, float]] = None,
    core_emotion: Optional[str] = None,
) -> CaseRepresentation:
    """
    Main extraction entry point for Stage 1.
    Transforms raw user text and optional emotion predictions into a rich,
    multi-dimensional CaseRepresentation without dropping facts or substituting generic fallbacks.
    """
    cleaned = (text or "").strip()
    if not cleaned:
        return CaseRepresentation(
            raw_text="",
            is_partial=True,
            ambiguity_level="sparse_insufficient",
            confidence_or_uncertainty=0.0,
            descriptive_summary="Empty input received.",
            unknowns=UnknownOrUnstatedInfo(missing_aspects=["All context and information"]),
        )

    nlp = get_spacy_nlp()
    doc = nlp(cleaned)

    # 1. Stated facts, emotions, behaviors, and thoughts
    stated_facts = _extract_stated_facts(doc, cleaned)
    stated_emotions = _extract_stated_emotions(doc, cleaned)
    stated_behaviors = _extract_stated_behaviors(doc, cleaned)
    stated_thoughts = _extract_stated_thoughts(doc, cleaned)

    # 2. Predicted emotions from model (kept strictly separate from stated emotions)
    predicted_emotions = []
    if emotion_scores:
        sorted_scores = sorted(emotion_scores.items(), key=lambda x: x[1], reverse=True)
        for label, score in sorted_scores[:3]:
            predicted_emotions.append(PredictedEmotion(
                label=label,
                score=float(score),
                source_model="roberta-goemotions-onnx",
            ))
    elif core_emotion:
        predicted_emotions.append(PredictedEmotion(
            label=core_emotion,
            score=1.0,
            source_model="inferred_core",
        ))

    # 3. Multi-dimensional appraisal hypotheses
    inferred_appraisals, interacting_concerns = _infer_appraisals(
        cleaned, stated_facts, stated_emotions, stated_thoughts
    )

    # 4. Uncertainty profile
    uncertainty = _infer_uncertainty(cleaned, inferred_appraisals)

    # 5. Controllability analysis
    controllability = _infer_controllability(stated_facts, inferred_appraisals)

    # 6. Support needs hypotheses
    support_needs = _infer_support_needs(inferred_appraisals, uncertainty)

    # 7. Explicit unknowns
    unknowns = _identify_unknowns(cleaned, stated_facts, stated_emotions, stated_thoughts, inferred_appraisals)

    # 8. Stated experience & formulation helpers
    user_goal = _extract_user_goal(cleaned, stated_thoughts)
    context_desc = _extract_context(cleaned, stated_facts, stated_behaviors)
    needs_or_concerns = _extract_needs_or_concerns(stated_facts, stated_emotions, inferred_appraisals, user_goal)
    tentative_interpretations = _infer_tentative_interpretations(inferred_appraisals, stated_facts, stated_emotions, stated_behaviors)
    ambiguity_level = _assess_ambiguity(cleaned, stated_facts, stated_emotions, stated_thoughts, stated_behaviors, inferred_appraisals, uncertainty)

    # 9. Build traceability map (Linking each inferred dimension to exact user substrings)
    traceability_map = {}
    for a in inferred_appraisals:
        traceability_map[f"appraisal_{a.dimension}"] = a.evidence_spans
    if uncertainty.evidence_spans:
        traceability_map["uncertainty"] = uncertainty.evidence_spans
    for f in stated_facts:
        traceability_map[f"fact_{f.category}_{f.text}"] = [f.source_span]
    for e in stated_emotions:
        traceability_map[f"emotion_{e.emotion_word}"] = [e.source_span]
    for b in stated_behaviors:
        traceability_map[f"behavior_{b}"] = [b]

    # 10. Descriptive summary (Grounding in stated facts, NEVER generic general_stress boilerplate)
    fact_texts = [f.text for f in stated_facts if f.category in ("actor", "milestone", "condition", "obligation", "event")]
    concerns_summary = ", ".join(interacting_concerns) if interacting_concerns else "emerging personal challenge"
    emotions_summary = ", ".join(f"{e.emotion_word}" for e in stated_emotions) if stated_emotions else "unspecified emotional tension"
    
    descriptive_summary = (
        f"Context involves {', '.join(fact_texts[:3]) if fact_texts else 'personal reflection'}. "
        f"Stated emotions: [{emotions_summary}]. "
        f"Active dimensions: [{concerns_summary}]."
    )

    is_partial = ambiguity_level in ("partial", "sparse_insufficient")
    confidence_val = 0.88 if ambiguity_level == "sufficient" else (0.65 if ambiguity_level == "partial" else 0.35)

    return CaseRepresentation(
        raw_text=cleaned,
        stated_facts=stated_facts,
        stated_emotions=stated_emotions,
        predicted_emotions=predicted_emotions,
        stated_thoughts=stated_thoughts,
        interacting_concerns=interacting_concerns,
        inferred_appraisals=inferred_appraisals,
        uncertainty=uncertainty,
        controllability=controllability,
        support_needs=support_needs,
        unknowns=unknowns,
        traceability_map=traceability_map,
        is_partial=is_partial,
        descriptive_summary=descriptive_summary,
        stated_behaviors=stated_behaviors,
        context=context_desc,
        needs_or_concerns=needs_or_concerns,
        tentative_interpretations=tentative_interpretations,
        user_goal=user_goal,
        confidence_or_uncertainty=confidence_val,
        ambiguity_level=ambiguity_level,
    )
