"""
Multi-Dimensional Case Representation Engine for MindVision.

Stage 1 Architecture:
Preserves user-stated facts, multiple interacting concerns, emotions, appraisals,
uncertainty, controllability, and support needs as separate, traceable fields.

Core Principles:
1. Strict separation of Stated Information (explicit) from Inferred Information (model hypotheses).
2. Explicit vs. Predicted emotions (user's words vs classifier scores).
3. Zero invention of visual details or premature psychological decisions (no forced CBT, no generic boilerplate).
4. Explicit tracking of Unknowns / Unstated information.
5. Full semantic traceability back to source text spans.
6. Robust handling of compound, ambiguous, misspelled, and partial inputs.
"""

import re
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Any, Optional, Tuple

import spacy

_nlp = None


def get_spacy_nlp():
    global _nlp
    if _nlp is None:
        try:
            _nlp = spacy.load("en_core_web_sm")
        except Exception:
            _nlp = spacy.blank("en")
            if "sentencizer" not in _nlp.pipe_names:
                _nlp.add_pipe("sentencizer")
    return _nlp


# =============================================================================
# 1. DATA CONTRACTS (Typed, Validated, Explicit Separation)
# =============================================================================

@dataclass
class StatedFact:
    """A concrete entity, actor, event, or condition explicitly mentioned by the user."""
    text: str
    category: str          # "actor", "milestone", "condition", "activity", "obligation", "event"
    source_span: str       # Exact verbatim substring from raw text
    start_char: int
    end_char: int

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class StatedEmotion:
    """An emotional state explicitly verbalized by the user."""
    emotion_word: str      # Exact verbatim word or lemma (e.g. "scared", "happy", "worried")
    valence: str           # "negative", "positive", "ambivalent"
    target: Optional[str]  # What the emotion is directed at (if syntactically attached)
    source_span: str       # Verbatim clause or phrase
    start_char: int
    end_char: int

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class PredictedEmotion:
    """An emotion prediction generated by an external classifier (e.g. RoBERTa ONNX)."""
    label: str
    score: float           # 0.0 to 1.0
    source_model: str = "roberta-goemotions-onnx"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class StatedThoughtOrClaim:
    """A verbatim thought, belief, evaluation, or question stated by the user."""
    statement: str         # e.g. "I haven't done enough", "I'll disappoint my family"
    source_span: str       # Exact verbatim substring
    start_char: int
    end_char: int

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class InferredAppraisal:
    """A model-inferred psychological appraisal, marked explicitly as a hypothesis."""
    dimension: str         # "social_comparison", "career_horizon_uncertainty", "evaluation_fear", "perceived_deficit", "locus_of_control", "temporal_focus"
    interpretation: str    # Human-readable explanation
    confidence: float      # 0.0 to 1.0
    status: str = "hypothesized"  # Always marked as hypothesis, never established fact
    evidence_spans: List[str] = field(default_factory=list)
    reasoning: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class UncertaintyProfile:
    """Assessment of genuine uncertainty vs. predictable facts."""
    has_uncertainty: bool
    uncertainty_type: Optional[str] = None  # "future_outcome", "relational_ambivalence", "decision_doubt", "unclear"
    is_inherently_unpredictable: bool = False
    preservation_required: bool = False     # If True, system must hold space, not force false reassurance
    evidence_spans: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class ControllabilityAnalysis:
    """Delineation of potentially controllable vs. uncontrollable factors as hypotheses."""
    potentially_controllable: List[str] = field(default_factory=list)
    potentially_uncontrollable: List[str] = field(default_factory=list)
    confidence: float = 0.5
    status: str = "inferred_hypothesis"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class SupportNeedsHypothesis:
    """Potential support modalities based on the case, without imposing CBT."""
    possible_needs: List[str] = field(default_factory=list)  # e.g. ["validation", "perspective_differentiation", "practical_structuring", "holding_space"]
    contraindications: List[str] = field(default_factory=list) # e.g. ["do_not_minimize_external_barrier", "do_not_force_premature_action"]
    status: str = "uncertain_hypothesis"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class UnknownOrUnstatedInfo:
    """Explicitly tracks what the user has NOT provided to prevent hallucinations."""
    missing_aspects: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class CaseRepresentation:
    """
    Comprehensive, multi-dimensional context representation.
    Preserves all user-stated information and isolates inferences with full traceability.
    """
    raw_text: str
    stated_facts: List[StatedFact] = field(default_factory=list)
    stated_emotions: List[StatedEmotion] = field(default_factory=list)
    predicted_emotions: List[PredictedEmotion] = field(default_factory=list)
    stated_thoughts: List[StatedThoughtOrClaim] = field(default_factory=list)
    interacting_concerns: List[str] = field(default_factory=list)
    inferred_appraisals: List[InferredAppraisal] = field(default_factory=list)
    uncertainty: UncertaintyProfile = field(default_factory=lambda: UncertaintyProfile(has_uncertainty=False))
    controllability: ControllabilityAnalysis = field(default_factory=ControllabilityAnalysis)
    support_needs: SupportNeedsHypothesis = field(default_factory=SupportNeedsHypothesis)
    unknowns: UnknownOrUnstatedInfo = field(default_factory=UnknownOrUnstatedInfo)
    traceability_map: Dict[str, List[str]] = field(default_factory=dict)
    is_partial: bool = False
    descriptive_summary: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# =============================================================================
# 2. LINGUISTIC EXTRACTION HELPERS (spaCy Parsing & Entity Mapping)
# =============================================================================

_ACTOR_KEYWORDS = {
    "friends": "actor", "friend": "actor", "family": "actor", "parents": "actor",
    "mother": "actor", "father": "actor", "mom": "actor", "dad": "actor",
    "supervisor": "actor", "boss": "actor", "colleague": "actor", "colleagues": "actor",
    "coworker": "actor", "peers": "actor", "peer": "actor", "partner": "actor",
    "boyfriend": "actor", "girlfriend": "actor", "team": "actor", "manager": "actor",
}

_MILESTONE_KEYWORDS = {
    "graduation": "milestone", "career": "domain", "job": "domain", "placement": "milestone",
    "placed": "milestone", "promotion": "milestone", "promoted": "milestone",
    "dating": "relationship", "relationship": "relationship", "partner": "relationship",
    "report": "document", "environmental report": "document", "planet": "macro_context",
    "interview": "event", "exam": "event", "test": "event", "presentation": "event",
    "meeting": "event", "assignments": "obligation", "manuscript": "creative_work",
    "project": "obligation", "dinner party": "event", "flare-up": "condition",
    "autoimmune": "condition", "laundry": "activity", "fridge": "condition",
}

_EMOTION_LEXICON = {
    "worried": ("negative", "worry/anxiety"),
    "worry": ("negative", "worry/anxiety"),
    "worries": ("negative", "worry/anxiety"),
    "scared": ("negative", "fear"),
    "fear": ("negative", "fear"),
    "afraid": ("negative", "fear"),
    "happy": ("positive", "joy/sympathy"),
    "glad": ("positive", "joy/sympathy"),
    "guilty": ("negative", "guilt"),
    "guilt": ("negative", "guilt"),
    "furious": ("negative", "anger"),
    "angry": ("negative", "anger"),
    "hopeless": ("negative", "despair"),
    "overwhelmed": ("negative", "overwhelm"),
    "disconnected": ("negative", "alienation"),
    "crying": ("negative", "acute_sadness"),
    "numb": ("negative", "blunting"),
    "anxious": ("negative", "anxiety"),
    "stressed": ("negative", "stress"),
    "confused": ("negative", "confusion"),
    "sad": ("negative", "sadness"),
}


def _extract_stated_facts(doc, raw_text: str) -> List[StatedFact]:
    facts = []
    lowered = raw_text.lower()

    # 1. Actors from keywords and noun chunks
    for token in doc:
        w = token.lemma_.lower()
        if w in _ACTOR_KEYWORDS:
            span = token.text
            start = token.idx
            end = start + len(span)
            facts.append(StatedFact(
                text=span,
                category=_ACTOR_KEYWORDS[w],
                source_span=span,
                start_char=start,
                end_char=end,
            ))

    # 2. Key domain, milestone, and condition entities
    for chunk in doc.noun_chunks:
        chunk_text = chunk.text.strip()
        chunk_lower = chunk_text.lower()
        for kw, cat in _MILESTONE_KEYWORDS.items():
            if re.search(rf"\b{re.escape(kw)}\b", chunk_lower):
                start = chunk.start_char
                end = chunk.end_char
                facts.append(StatedFact(
                    text=chunk_text,
                    category=cat,
                    source_span=chunk_text,
                    start_char=start,
                    end_char=end,
                ))
                break

    event_patterns = [
        (r"\bfriends\s+(are\s+)?getting\s+placed\b", "event", "friends getting placed"),
        (r"\bdisappoint\s+(my\s+)?family\b", "stated_concern", "concern: disappointing family"),
        (r"\bautoimmune\s+flare-up\s+returned\b", "condition", "autoimmune flare-up returned"),
        (r"\bgave\s+credit\s+for\s+my\s+.*\s+project\b", "event", "supervisor gave credit to colleague"),
        (r"\bpromoted\s+to\s+lead\b", "milestone", "promoted to lead"),
        (r"\btaking\s+care\s+of\s+my\s+aging\s+mother\b", "event", "caregiving for aging mother"),
        (r"\bsnapped\s+at\s+her\b", "event", "snapped at mother"),
        (r"\bmanuscript\s+was\s+rejected\b", "event", "manuscript rejected"),
        (r"\bdinner\s+party\s+.*\s+didn'?t\s+invite\s+me\b", "event", "friends dinner party without invitation"),
        (r"\bsitting\s+on\s+the\s+floor\b", "behavioral_state", "sitting on floor"),
        (r"\bcan barely get out of bed\b", "physical_state", "unable to get out of bed"),
        (r"\b(drained\s+all\s+my\s+energy|completely\s+drained|exhausted)\b", "physical_state", "physical exhaustion"),
        (r"\b(paralyzed|unable\s+to\s+move)\b", "behavioral_state", "behavioral immobility"),
    ]
    for pattern, cat, label in event_patterns:
        m = re.search(pattern, lowered)
        if m:
            span = raw_text[m.start():m.end()]
            facts.append(StatedFact(
                text=label,
                category=cat,
                source_span=span,
                start_char=m.start(),
                end_char=m.end(),
            ))

    # Deduplicate by start/end char
    seen = set()
    deduped = []
    for f in facts:
        key = (f.start_char, f.end_char)
        if key not in seen:
            seen.add(key)
            deduped.append(f)
    return deduped


def _extract_stated_emotions(doc, raw_text: str) -> List[StatedEmotion]:
    emotions = []
    lowered = raw_text.lower()

    for token in doc:
        lemma = token.lemma_.lower()
        word = token.text.lower()
        key = word if word in _EMOTION_LEXICON else (lemma if lemma in _EMOTION_LEXICON else None)

        if key:
            valence, label = _EMOTION_LEXICON[key]
            start = token.idx
            end = start + len(token.text)
            target = None

            # Look for syntactic target (e.g. "worried about career", "scared that...")
            for child in token.children:
                if child.dep_ in ("prep", "ccomp", "dobj"):
                    target_span = raw_text[child.idx:child.idx + len(child.subtree_text) if hasattr(child, "subtree_text") else child.idx + 25]
                    target = target_span.strip()
                    break

            emotions.append(StatedEmotion(
                emotion_word=token.text,
                valence=valence,
                target=target,
                source_span=token.sent.text.strip() if token.sent else token.text,
                start_char=start,
                end_char=end,
            ))

    # Deduplicate
    seen = set()
    deduped = []
    for e in emotions:
        key = (e.start_char, e.end_char)
        if key not in seen:
            seen.add(key)
            deduped.append(e)
    return deduped


def _extract_stated_thoughts(doc, raw_text: str) -> List[StatedThoughtOrClaim]:
    thoughts = []
    lowered = raw_text.lower()

    thought_patterns = [
        r"\bi\s+haven'?t\s+done\s+enough\b",
        r"\bi'?ll\s+disappoint\s+(my\s+)?family\b",
        r"\bi\s+can'?t\s+be\s+productive\b",
        r"\bcan barely get out of bed\b",
        r"\bi\s+feel\s+completely\s+powerless\b",
        r"\bi\s+don'?t\s+know\s+whether\s+to\s+try\s+harder\s+or\s+let\s+go\b",
        r"\bi\s+feel\s+like\s+an?\s+(absolute\s+)?fraud\b",
        r"\bthey\s+will\s+realize\s+i\s+have\s+no\s+idea\b",
        r"\bi\s+feel\s+like\s+an\s+awful\s+person\b",
        r"\bwhat'?s\s+the\s+point\s+of\s+planning\b",
        r"\bplanet\s+is\s+burning\b",
        r"\bi\s+simply\s+have\s+no\s+talent\b",
        r"\bwasted\s+years\s+of\s+my\s+life\b",
        r"\bwondering\s+what'?s\s+wrong\s+with\s+me\b",
        r"\bunable\s+to\s+move\b",
    ]

    for pat in thought_patterns:
        m = re.search(pat, lowered)
        if m:
            span = raw_text[m.start():m.end()]
            thoughts.append(StatedThoughtOrClaim(
                statement=span,
                source_span=span,
                start_char=m.start(),
                end_char=m.end(),
            ))

    return thoughts


# =============================================================================
# 3. MULTI-DIMENSIONAL APPRAISAL HEURISTICS (Marked Explicitly as Hypotheses)
# =============================================================================

def _infer_appraisals(
    raw_text: str,
    facts: List[StatedFact],
    emotions: List[StatedEmotion],
    thoughts: List[StatedThoughtOrClaim],
) -> Tuple[List[InferredAppraisal], List[str]]:
    appraisals = []
    concerns = []
    lowered = raw_text.lower()

    # 1. Social Comparison & Peer Pacing
    if re.search(r"\b(friends|peers|colleagues|everyone)\b.*\b(placed|succeeding|doing better|invite|dinner)\b", lowered) or \
       re.search(r"\bkeep\s+up\s+with\s+(my\s+)?peers\b", lowered):
        evidence = [f.source_span for f in facts if f.category in ("actor", "event") and any(w in f.source_span.lower() for w in ["friends", "peers", "placed", "invite"])]
        if not evidence:
            m = re.search(r"\b(friends|peers|colleagues|everyone)[^.?!]*\b", lowered)
            evidence = [raw_text[m.start():m.end()].strip()] if m else ["Mention of peer pacing or social circle"]
        appraisals.append(InferredAppraisal(
            dimension="social_comparison",
            interpretation="Evaluation of personal pacing against observed peer progress or social inclusion.",
            confidence=0.85,
            evidence_spans=evidence,
            reasoning="User references external peers and compares personal status or involvement.",
        ))
        concerns.append("peer_comparison_and_pacing")

    # 2. Career Horizon / Future Transition
    if re.search(r"\b(career|graduation|graduate|job|placed|placement|future|promotion)\b", lowered):
        evidence = [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["career", "graduation", "job", "placed", "promotion"])]
        if not evidence:
            m = re.search(r"\b(career|graduation|future)[^.?!]*\b", lowered)
            evidence = [raw_text[m.start():m.end()].strip()] if m else ["Career or future transition referenced"]
        appraisals.append(InferredAppraisal(
            dimension="career_horizon_uncertainty",
            interpretation="Anticipatory concern regarding professional transition and upcoming milestones.",
            confidence=0.88,
            evidence_spans=evidence,
            reasoning="User identifies a major impending transition into the workforce or professional role.",
        ))
        concerns.append("career_transition_uncertainty")

    # 3. Filial / Interpersonal Expectation Pressure
    if re.search(r"\b(disappoint\s+(my\s+)?(family|parents|mother|father|mom|dad))\b", lowered) or \
       re.search(r"\b(aging\s+mother|snapped\s+at\s+her)\b", lowered):
        evidence = [t.statement for t in thoughts if "disappoint" in t.statement.lower()] or \
                   [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["family", "mother", "aging"])]
        appraisals.append(InferredAppraisal(
            dimension="evaluation_fear",
            interpretation="Concern regarding failing expectations of loved ones or feeling guilt over relational care.",
            confidence=0.82,
            evidence_spans=evidence,
            reasoning="User explicitly articulates fear of letting family down or guilt over caregiving interactions.",
        ))
        concerns.append("family_expectation_pressure")

    # 4. Perceived Self-Deficit
    if re.search(r"\b(haven'?t\s+done\s+enough|can'?t\s+be\s+productive|no\s+talent|awful\s+person|fraud|what'?s\s+wrong\s+with\s+me)\b", lowered):
        evidence = [t.statement for t in thoughts if any(w in t.statement.lower() for w in ["enough", "productive", "talent", "awful", "fraud", "wrong"])]
        appraisals.append(InferredAppraisal(
            dimension="perceived_deficit",
            interpretation="Internalized self-evaluation attributing difficulty to personal inadequacy or insufficient effort.",
            confidence=0.80,
            evidence_spans=evidence,
            reasoning="User verbalizes a feeling of falling short, being inadequate, or lacking necessary output.",
        ))
        concerns.append("self_deficit_evaluation")

    # 5. External Workplace Injustice / Powerlessness
    if re.search(r"\b(supervisor|boss|manager)\b.*\b(credit|stole|took|unfair)\b", lowered) or \
       re.search(r"\bfeel(ing)?\s+completely\s+powerless\b", lowered):
        evidence = [f.source_span for f in facts if "supervisor" in f.source_span.lower()] or ["Feeling powerless over workplace action"]
        appraisals.append(InferredAppraisal(
            dimension="systemic_injustice",
            interpretation="Experience of unacknowledged labor or unaddressed institutional unfairness.",
            confidence=0.90,
            evidence_spans=evidence,
            reasoning="User describes an external violation of professional fairness by authority figure.",
        ))
        concerns.append("workplace_injustice")

    # 6. Physical Illness / Bodily Limitation
    if re.search(r"\b(autoimmune|flare-up|sick|bed|chronic|illness|pain)\b", lowered):
        evidence = [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["flare-up", "autoimmune", "bed"])]
        appraisals.append(InferredAppraisal(
            dimension="bodily_limitation",
            interpretation="Legitimate physiological depletion or health flare-up restricting physical capacity.",
            confidence=0.92,
            evidence_spans=evidence,
            reasoning="User explicitly identifies biological symptoms preventing physical activity.",
        ))
        concerns.append("bodily_illness_constraint")

    # 7. Executive Dysfunction / Behavioral Paralysis
    if re.search(r"\b(assignments\s+due|laundry|fridge|sitting\s+on\s+the\s+floor|unable\s+to\s+move|four\s+hours)\b", lowered):
        evidence = [f.source_span for f in facts if any(w in f.source_span.lower() for w in ["assignments", "laundry", "floor"])]
        appraisals.append(InferredAppraisal(
            dimension="executive_freeze",
            interpretation="Cognitive freeze / task accumulation resulting in behavioral immobility.",
            confidence=0.88,
            evidence_spans=evidence,
            reasoning="User describes competing tasks coupled with several hours of physical immobility.",
        ))
        concerns.append("executive_freeze")

    return appraisals, concerns


def _infer_uncertainty(raw_text: str, appraisals: List[InferredAppraisal]) -> UncertaintyProfile:
    lowered = raw_text.lower()
    dims = {a.dimension for a in appraisals}

    # Relational ambivalence
    if re.search(r"\b(don'?t\s+know\s+whether\s+to\s+try\s+harder\s+or\s+let\s+go|disconnected|dating|relationship)\b", lowered):
        return UncertaintyProfile(
            has_uncertainty=True,
            uncertainty_type="relational_ambivalence",
            is_inherently_unpredictable=True,
            preservation_required=True,
            evidence_spans=["I don't know whether to try harder or let go"],
        )

    # Climate / Macro existential
    if re.search(r"\b(planet\s+is\s+burning|hopeless\s+about\s+the\s+future|environmental\s+report)\b", lowered):
        return UncertaintyProfile(
            has_uncertainty=True,
            uncertainty_type="macro_existential",
            is_inherently_unpredictable=True,
            preservation_required=True,
            evidence_spans=["hopeless about the future", "planet is burning"],
        )

    # Future outcome / Career horizon
    if "career_horizon_uncertainty" in dims or re.search(r"\b(future|career|after graduation|what will happen)\b", lowered):
        return UncertaintyProfile(
            has_uncertainty=True,
            uncertainty_type="future_outcome",
            is_inherently_unpredictable=True,
            preservation_required=True,
            evidence_spans=["worried about my career after graduation"] if "career" in lowered else ["future"],
        )

    return UncertaintyProfile(has_uncertainty=False)


def _infer_controllability(facts: List[StatedFact], appraisals: List[InferredAppraisal]) -> ControllabilityAnalysis:
    dims = {a.dimension for a in appraisals}
    controllable = []
    uncontrollable = []

    if "career_horizon_uncertainty" in dims:
        controllable.append("Individual job applications, interview preparation, and personal daily pacing")
        uncontrollable.append("Macro hiring market timelines and specific employer decision schedules")

    if "social_comparison" in dims:
        uncontrollable.append("Other people's timelines, placements, and milestones")
        controllable.append("Focusing attention on personal growth and self-chosen criteria")

    if "evaluation_fear" in dims:
        uncontrollable.append("Family members' immediate emotional reactions or unspoken expectations")
        controllable.append("Communicating honestly about one's efforts and setting compassionate boundaries")

    if "systemic_injustice" in dims:
        uncontrollable.append("Supervisor's past behavior during the meeting")
        controllable.append("Documenting work, speaking with HR/mentors, or establishing project boundaries")

    if "bodily_limitation" in dims:
        uncontrollable.append("Biological flare-up and involuntary physical exhaustion")
        controllable.append("Permitting restful recovery and hydration without self-blame")

    if "executive_freeze" in dims:
        controllable.append("Selecting a single 2-minute entry task (e.g. drinking water, clearing one item)")
        uncontrollable.append("Completing all assignments and household chores all at once")

    return ControllabilityAnalysis(
        potentially_controllable=controllable,
        potentially_uncontrollable=uncontrollable,
        confidence=0.75 if (controllable or uncontrollable) else 0.3,
    )


def _infer_support_needs(
    appraisals: List[InferredAppraisal],
    uncertainty: UncertaintyProfile,
) -> SupportNeedsHypothesis:
    dims = {a.dimension for a in appraisals}
    possible_needs = []
    contraindications = []

    if "bodily_limitation" in dims:
        possible_needs.append("empathetic_validation")
        possible_needs.append("permission_to_rest")
        contraindications.append("do_not_frame_physical_illness_as_cognitive_distortion")
        contraindications.append("do_not_demand_productivity_steps")

    if "systemic_injustice" in dims:
        possible_needs.append("validation_of_injustice")
        possible_needs.append("boundary_and_objective_options")
        contraindications.append("do_not_gaslight_or_reframe_supervisor_behavior")

    if uncertainty.uncertainty_type == "relational_ambivalence":
        possible_needs.append("holding_space_for_ambivalence")
        possible_needs.append("reflective_clarification")
        contraindications.append("do_not_force_premature_decision_or_false_certainty")

    if "social_comparison" in dims and "career_horizon_uncertainty" in dims:
        possible_needs.append("values_clarification_and_pacing_differentiation")
        possible_needs.append("decoupling_self_worth_from_peer_timeline")
        contraindications.append("do_not_dismiss_family_concern_as_irrational")

    if "executive_freeze" in dims:
        possible_needs.append("somatic_grounding_and_micro_step")
        contraindications.append("do_not_overwhelm_with_multi_step_planning")

    return SupportNeedsHypothesis(
        possible_needs=possible_needs or ["open_reflective_exploration"],
        contraindications=contraindications,
    )


def _identify_unknowns(
    raw_text: str,
    facts: List[StatedFact],
    emotions: List[StatedEmotion],
    thoughts: List[StatedThoughtOrClaim],
    appraisals: List[InferredAppraisal],
) -> UnknownOrUnstatedInfo:
    dims = {a.dimension for a in appraisals}
    missing = []

    if "career_horizon_uncertainty" in dims:
        missing.append("Specific career field, target roles, or active applications")
        missing.append("What 'doing enough' specifically means to the user")

    if "evaluation_fear" in dims:
        missing.append("Family's actual stated expectations vs. internal anticipated dread")

    if "social_comparison" in dims:
        missing.append("User's own personal criteria for success independent of friends")

    if "bodily_limitation" in dims:
        missing.append("Current medical guidance or accommodation options")

    if "systemic_injustice" in dims:
        missing.append("Workplace reporting structures or written documentation of project authorship")

    if not facts:
        missing.append("Concrete situational trigger or context")

    missing.append("User's preferred support modality (listening vs. planning vs. perspective)")

    return UnknownOrUnstatedInfo(missing_aspects=missing)


# =============================================================================
# 4. PRIMARY EXTRACTION PIPELINE
# =============================================================================

def extract_case_representation(
    text: str,
    emotion_scores: Optional[Dict[str, float]] = None,
    core_emotion: Optional[str] = None,
) -> CaseRepresentation:
    """
    Main extraction entry point for Stage 1.
    Transforms raw user text and optional emotion predictions into a rich,
    multi-dimensional CaseRepresentation without dropping facts or substituting generic fallbacks.
    """
    cleaned = (text or "").strip()
    if not cleaned:
        return CaseRepresentation(
            raw_text="",
            is_partial=True,
            descriptive_summary="Empty input received.",
            unknowns=UnknownOrUnstatedInfo(missing_aspects=["All context and information"]),
        )

    nlp = get_spacy_nlp()
    doc = nlp(cleaned)

    # 1. Stated facts, emotions, and thoughts
    stated_facts = _extract_stated_facts(doc, cleaned)
    stated_emotions = _extract_stated_emotions(doc, cleaned)
    stated_thoughts = _extract_stated_thoughts(doc, cleaned)

    # 2. Predicted emotions from model (kept strictly separate from stated emotions)
    predicted_emotions = []
    if emotion_scores:
        sorted_scores = sorted(emotion_scores.items(), key=lambda x: x[1], reverse=True)
        for label, score in sorted_scores[:3]:
            predicted_emotions.append(PredictedEmotion(
                label=label,
                score=float(score),
                source_model="roberta-goemotions-onnx",
            ))
    elif core_emotion:
        predicted_emotions.append(PredictedEmotion(
            label=core_emotion,
            score=1.0,
            source_model="inferred_core",
        ))

    # 3. Multi-dimensional appraisal hypotheses
    inferred_appraisals, interacting_concerns = _infer_appraisals(
        cleaned, stated_facts, stated_emotions, stated_thoughts
    )

    # 4. Uncertainty profile
    uncertainty = _infer_uncertainty(cleaned, inferred_appraisals)

    # 5. Controllability analysis
    controllability = _infer_controllability(stated_facts, inferred_appraisals)

    # 6. Support needs hypotheses
    support_needs = _infer_support_needs(inferred_appraisals, uncertainty)

    # 7. Explicit unknowns
    unknowns = _identify_unknowns(cleaned, stated_facts, stated_emotions, stated_thoughts, inferred_appraisals)

    # 8. Build traceability map (Linking each inferred dimension to exact user substrings)
    traceability_map = {}
    for a in inferred_appraisals:
        traceability_map[f"appraisal_{a.dimension}"] = a.evidence_spans
    if uncertainty.evidence_spans:
        traceability_map["uncertainty"] = uncertainty.evidence_spans
    for f in stated_facts:
        traceability_map[f"fact_{f.category}_{f.text}"] = [f.source_span]
    for e in stated_emotions:
        traceability_map[f"emotion_{e.emotion_word}"] = [e.source_span]

    # 9. Descriptive summary (Grounding in stated facts, NEVER generic general_stress boilerplate)
    fact_texts = [f.text for f in stated_facts if f.category in ("actor", "milestone", "condition")]
    concerns_summary = ", ".join(interacting_concerns) if interacting_concerns else "emerging personal challenge"
    emotions_summary = ", ".join(f"{e.emotion_word}" for e in stated_emotions) if stated_emotions else "unspecified emotional tension"
    
    descriptive_summary = (
        f"Context involves {', '.join(fact_texts[:3]) if fact_texts else 'personal reflection'}. "
        f"Stated emotions: [{emotions_summary}]. "
        f"Active dimensions: [{concerns_summary}]."
    )

    is_partial = len(stated_facts) == 0 and len(stated_emotions) <= 1 and len(stated_thoughts) == 0 and not uncertainty.has_uncertainty

    return CaseRepresentation(
        raw_text=cleaned,
        stated_facts=stated_facts,
        stated_emotions=stated_emotions,
        predicted_emotions=predicted_emotions,
        stated_thoughts=stated_thoughts,
        interacting_concerns=interacting_concerns,
        inferred_appraisals=inferred_appraisals,
        uncertainty=uncertainty,
        controllability=controllability,
        support_needs=support_needs,
        unknowns=unknowns,
        traceability_map=traceability_map,
        is_partial=is_partial,
        descriptive_summary=descriptive_summary,
    )
